version: "2"

linters:
  default: standard
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of `.*.Close` is not checked"

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  relative-path-mode: cfg
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false
