name: CI

on:
  push:
    branches:
      - feature/**
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: ./go.mod

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: v2.0
          args: --timeout=5m --config=./.golangci.yml

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: ./go.mod

      - name: Build binary
        run: go build -v -o ./bin/main ./cmd/*

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: ./go.mod

      - name: Run unit tests
        run: go test -v -race -cover ./...
